services:
  postgres:
    image: postgres:16-alpine
    container_name: booking_postgres
    environment:
      POSTGRES_DB: booking_service
      POSTGRES_USER: booking
      POSTGRES_PASSWORD: booking
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U booking -d booking_service"]
      interval: 5s
      timeout: 5s
      retries: 10

  backend:
    build: .
    container_name: booking_backend
    environment:
      POSTGRES_DB: booking_service
      POSTGRES_USER: booking
      POSTGRES_PASSWORD: booking
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      DJANGO_DEBUG: "true"
      DJANGO_ALLOWED_HOSTS: "*"
      SEED_DEMO_DATA: "true"
    ports:
      - "8000:8000"
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - .:/app

volumes:
  postgres_data:
