# Generated by Django 6.0 on 2026-09-09 12:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id_employee', models.AutoField(primary_key=True, serialize=False)),
                ('last_name', models.CharField(max_length=100)),
                ('first_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(blank=True, max_length=100, null=True)),
                ('position', models.CharField(max_length=100)),
                ('phone', models.CharField(blank=True, max_length=32, null=True, unique=True)),
                ('hire_date', models.DateField()),
            ],
            options={
                'db_table': 'employees',
            },
        ),
        migrations.CreateModel(
            name='EmployeeRole',
            fields=[
                ('id_role', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'db_table': 'employeeroles',
            },
        ),
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id_guest', models.AutoField(primary_key=True, serialize=False)),
                ('last_name', models.CharField(max_length=100)),
                ('first_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(blank=True, max_length=100, null=True)),
                ('phone', models.CharField(blank=True, max_length=32, null=True, unique=True)),
                ('email', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('passport_number', models.CharField(blank=True, max_length=32, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'guests',
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id_room', models.AutoField(primary_key=True, serialize=False)),
                ('room_number', models.CharField(max_length=20, unique=True)),
                ('floor', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(default='available', max_length=20)),
            ],
            options={
                'db_table': 'rooms',
            },
        ),
        migrations.CreateModel(
            name='RoomType',
            fields=[
                ('id_type', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('price_per_night', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'roomtypes',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id_service', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'services',
            },
        ),
        migrations.CreateModel(
            name='EmployeeRoleAssignment',
            fields=[
                ('pk', models.CompositePrimaryKey('id_employee', 'id_role', blank=True, editable=False, primary_key=True, serialize=False)),
                ('id_employee', models.ForeignKey(db_column='id_employee', on_delete=django.db.models.deletion.CASCADE, related_name='role_assignments', to='main.employee')),
                ('id_role', models.ForeignKey(db_column='id_role', on_delete=django.db.models.deletion.CASCADE, related_name='role_assignments', to='main.employeerole')),
            ],
            options={
                'db_table': 'employeeroleassignments',
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id_booking', models.BigAutoField(primary_key=True, serialize=False)),
                ('check_in', models.DateField()),
                ('check_out', models.DateField()),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id_guest', models.ForeignKey(db_column='id_guest', on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='main.guest')),
                ('id_room', models.ForeignKey(db_column='id_room', on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='main.room')),
            ],
            options={
                'db_table': 'bookings',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id_payment', models.BigAutoField(primary_key=True, serialize=False)),
                ('payment_date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('method', models.CharField(max_length=20)),
                ('status', models.CharField(default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('id_booking', models.ForeignKey(db_column='id_booking', on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='main.booking')),
            ],
            options={
                'db_table': 'payments',
            },
        ),
        migrations.CreateModel(
            name='RoomCleaning',
            fields=[
                ('id_cleaning', models.BigAutoField(primary_key=True, serialize=False)),
                ('cleaning_date', models.DateField()),
                ('cleaning_start', models.DateTimeField()),
                ('cleaning_end', models.DateTimeField(blank=True, null=True)),
                ('cleaning_status', models.CharField(default='scheduled', max_length=20)),
                ('cleaning_type', models.CharField(default='routine', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('id_employee', models.ForeignKey(db_column='id_employee', on_delete=django.db.models.deletion.PROTECT, related_name='cleanings', to='main.employee')),
                ('id_room', models.ForeignKey(db_column='id_room', on_delete=django.db.models.deletion.CASCADE, related_name='cleanings', to='main.room')),
            ],
            options={
                'db_table': 'roomcleanings',
            },
        ),
        migrations.AddField(
            model_name='room',
            name='id_type',
            field=models.ForeignKey(db_column='id_type', on_delete=django.db.models.deletion.PROTECT, related_name='rooms', to='main.roomtype'),
        ),
        migrations.CreateModel(
            name='BookingService',
            fields=[
                ('pk', models.CompositePrimaryKey('id_booking', 'id_service', blank=True, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.IntegerField(default=1)),
                ('id_booking', models.ForeignKey(db_column='id_booking', on_delete=django.db.models.deletion.CASCADE, related_name='booking_services', to='main.booking')),
                ('id_service', models.ForeignKey(db_column='id_service', on_delete=django.db.models.deletion.CASCADE, related_name='booking_services', to='main.service')),
            ],
            options={
                'db_table': 'bookingservices',
            },
        ),
    ]
