# Generated by Django 6.0 on 2026-09-10 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['-created_at'], name='idx_bookings_created_at'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['status', '-created_at'], name='idx_bookings_status_created'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['status', 'check_in'], name='idx_bookings_status_check_in'),
        ),
    ]
